"use server";

import { db } from "@/lib/db";
import { revalidatePath } from "next/cache";

export async function getUsers() {
  const result = await db.query('SELECT * FROM "User" ORDER BY create_at DESC');
  return result.rows;
}

export async function deleteUser(id: string) {
  await db.query('DELETE FROM "User" WHERE id = $1', [id]);
  revalidatePath("/user");
}

export async function getUserById(id: string) {
  const result = await db.query('SELECT * FROM "User" WHERE id = $1', [id]);
  return result.rows[0];
}

export async function createUser(data: { username: string; level: string; password?: string }) {
  // Using simple insert, uuid is generated by db (default uuid()) if omitted?
  // Let's rely on db to generate uuid
  await db.query(
    'INSERT INTO "User" (username, password, level) VALUES ($1, $2, $3)',
    [data.username, data.password || '123456', data.level]
  );
  revalidatePath("/user");
}

export async function updateUser(id: string, data: { username: string; level: string; balance?: number }) {
  await db.query(
    'UPDATE "User" SET username = $1, level = $2, balance = $3 WHERE id = $4',
    [data.username, data.level, data.balance ?? 0, id]
  );
  revalidatePath("/user");
}
